---
title: "README"
author: "Meredith Dart"
date: "16 January 2017"
output: html_document
---

###Using the dataset indicated, the script run_analysis.R performs the following tasks:

* Takes an argument, "directory", which is used as the working directory, assumed to be the parent of the directories created by the unzip process of the data set archive

* Takes an optional argument, "outputfile", which is used as the name of the output file if entered, otherwise uses "calc_means.txt" as the output filename.

* Reads in the training and test data sets, assigning the subject id to each observation as a separate column.

* Labels the features with the names provided in the features.txt file. These names are consistent abbreviations of the various measurements and calculations derived from the accelerometer and gyroscope signals generated by the phone, and are further expanded in the code book, CodeBook.Rmd

* Subsets the original dataset to include only those features containing "mean" (mean) or "std" (standard deviation) in the name. This includes features containing the name "meanFreq", as this indicates a weighted average frequency calculation from the raw data signals.

* Replaces the activity IDs with the descriptive labels provided in the activity_labels.txt file.

* Creates a tidy data file, calc_means.txt (unless overriden by the entered argument), containing the average of each selected feature by subject and activity. The output file meets the tidy data principles as laid out in the Hadley Wickham paper cited in the course materials, with a struture as laid out in the CodeBook markdown document, where each variable is in a separate column, each obervation forms a row, and the output dataset contains a single type of observation.

The output summary file may be read in with the following command:

```{r}
data <- read.table("calc_means.txt", header = TRUE)
View(data)
```

